### ISSUE TITLE
about your article "Optimizing PHP performance by using fully-qualified function calls"

### ISSUE THREAD

**Issue by a2rette** [veewee/veewee.github.io#16]
Hi,

Thank you for this very interesting article.
I recently refactor all the global functions of my project into well organized namespaced functions, and i'm wondering if i have not made a mistake there : Everytime i put some code in a namespace, the resolution time of all global functions is altered :/
That makes me sad...

Your article dates back from 2016, 7 years now, would there have been any news about that ?
Do i have to prefix all PHP global functions with a slash ? (apart from the other solutions you suggest then)

Best regards,
Arnaud

**Comment by veewee** [comment]
Hello Arnaud,

Thanks for reaching out.
The article is 7 years old and still relevant: PHP still adds an additional opcode - with reason.

So yes, you'll need to add either a `\` before the global function call - or import the function if you want to have these micro optimalisations in place.
Nowadays, there are a lot of tools doing the heavy lifting for you so that you don't have to care about this.

Of course, the win is quite limited in regular projects. So if you don't do this, you might even never notice it is slower.

The resolution time is not "fixed" and will always be more or less different in any case.
